-- Drug Refer Agent v1.6.0 API database migration
-- Apply once to the db_drug_refer database before rolling out the agent.

CREATE TABLE IF NOT EXISTS `s_drugitems` (
  `icode` varchar(7) NOT NULL DEFAULT '',
  `name` varchar(200) DEFAULT NULL,
  `strength` varchar(50) DEFAULT NULL,
  `units` varchar(50) DEFAULT NULL,
  `dosageform` varchar(100) DEFAULT NULL,
  `drugnote` varchar(150) DEFAULT NULL,
  `use_right` char(1) DEFAULT NULL,
  `must_paid` char(1) DEFAULT NULL,
  `istatus` char(1) DEFAULT NULL,
  `access_level` int(11) DEFAULT NULL,
  `paidst` char(2) DEFAULT NULL,
  `displaycolor` int(11) DEFAULT NULL,
  `price_lock` char(1) DEFAULT NULL,
  `icode_guid` varchar(38) DEFAULT NULL,
  `ename` varchar(150) DEFAULT NULL,
  `cost` double(15,3) DEFAULT NULL,
  `income` char(2) DEFAULT NULL,
  `hos_guid` varchar(38) DEFAULT NULL,
  `hos_guid_ext` varchar(64) DEFAULT NULL,
  `is_medication` char(1) DEFAULT NULL,
  `use_paidst` char(1) DEFAULT NULL,
  `is_medsupply` char(1) DEFAULT NULL,
  `sub_income` varchar(3) DEFAULT NULL,
  `oldcode` varchar(15) DEFAULT NULL,
  `displaycolor_focus` int(11) DEFAULT NULL,
  `billcode` varchar(10) DEFAULT NULL,
  `billnumber` varchar(15) DEFAULT NULL,
  `nhso_adp_type_id` int(11) DEFAULT NULL,
  `nhso_adp_code` varchar(15) DEFAULT NULL,
  `unitprice` double(15,3) DEFAULT NULL,
  `highcost` varchar(1) DEFAULT 'N',
  `tpu_code_list` varchar(200) DEFAULT NULL,
  `sks_drug_code` varchar(25) DEFAULT NULL,
  `drugaccount` varchar(2) DEFAULT NULL,
  `sks_dfs_code` varchar(50) DEFAULT NULL,
  `drugcategory` varchar(150) DEFAULT NULL,
  `sks_product_category_id` int(11) DEFAULT NULL,
  `icd9cm` varchar(7) DEFAULT NULL,
  `csmbs_claim_cat` varchar(1) DEFAULT NULL,
  `ipd_price` double(15,3) DEFAULT NULL,
  `drg_chrgitem_id` varchar(2) DEFAULT NULL,
  `export_opd` varchar(1) DEFAULT NULL,
  `export_ipd` varchar(1) DEFAULT NULL,
  `max_qty` int(11) DEFAULT NULL,
  `max_qty_ipd` int(11) DEFAULT NULL,
  `stdprice` double(15,3) DEFAULT NULL,
  `did` varchar(30) DEFAULT NULL,
  `note` varchar(100) DEFAULT NULL,
  PRIMARY KEY (`icode`),
  KEY `ix_name` (`name`),
  KEY `ix_access` (`access_level`),
  KEY `ix_status` (`istatus`),
  KEY `ix_nsu` (`name`,`strength`,`units`),
  KEY `ix_icode_guid` (`icode_guid`),
  KEY `ix_hos_guid_ext` (`hos_guid_ext`),
  KEY `ix_search1` (`is_medication`,`istatus`,`name`,`icode`),
  KEY `ix_search1_index` (`icode`,`is_medication`,`istatus`,`name`),
  KEY `ix_nsu_index` (`strength`,`units`,`name`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT INTO `option_his_query` (
  `query_id`, `his_name`, `his_type`, `query_text`,
  `table_insert_name`, `active`
) VALUES
  (3, 'hosxp', 'mysql', 'SELECT * FROM drugitems', 'drugitems', 'Y'),
  (4, 'hosxp', 'mysql', 'SELECT * FROM s_drugitems', 's_drugitems', 'Y')
ON DUPLICATE KEY UPDATE
  `query_text` = VALUES(`query_text`),
  `table_insert_name` = VALUES(`table_insert_name`),
  `active` = 'Y';
